services:
  find-suri:
    build:
      context: .
    ports:
      - "80:80"
      - "8080:8080"
      - "2019:2019"
      - "443:443"
    environment:
      DB_CONNECTION: sqlite
      DEFAULT_USER: "test"
      DEFAULT_EMAIL: "docker@test.com"
      DEFAULT_PASSWORD: "thisismypassword"
      APP_TIMEZONE: UTC
      TOP_NAVIGATION: 0
      DISABLE_TOP_BAR: 0
      BREADCRUMBS: 1
      SPA: 1
      THEME_COLOR: Stone
      FRANKEN_HOST: "localhost"
      APP_URL: "http://localhost:80"
      ASSET_URL: "http://localhost:80"
      PYTHON_RUN_COMMAND_OR_PATH: "/app/face_recognition/bin/python3"
